language: node_js
node_js:
  - 10

deploy:
  provider: gae
  keyfile: crient-secret.json
  project: global-snow-269714
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - openssl aes-256-cbc -K $encrypted_89c6bc192d4f_key -iv $encrypted_89c6bc192d4f_iv -in crient-secret.json.enc -out crient-secret.json -d
install:
  - yarn
  - yarn build
cache:
  yarn: true
env:
  - BASE_URL=http://localhost:3000
  - API_DEV_URL=http://localhost:4000
  - API_PROD_URL=https://flask-test-dot-global-snow-269714.appspot.com

